// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char DEVICE_LOGIN_NAME[]  = SECRET_DEVICE_LOGIN_NAME; // Device Login Name
const char SSID[]               = SECRET_SSID;              // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;     // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]         = SECRET_DEVICE_KEY;        // Secret device password

bool isOnline;
bool refresh;
bool sendWoLPacket;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(isOnline, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(refresh, READWRITE, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sendWoLPacket, READWRITE, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
